import { prisma } from '../prisma'
import { Prisma } from '@prisma/client'
export type CartItem={productId:string;quantity:number;addonIds:string[]}
export async function completeOrder(input:{userId:string;customerId?:string|null;items:CartItem[];discountType?:'FIXED'|'PERCENTAGE';discountValue?:number;paymentMethod:'CASH'|'ONLINE';amountReceived?:number;paymentProofPath?:string|null}){
 return prisma.$transaction(async tx=>{
  if(!input.items.length) throw new Error('Add at least one product to the order.')
  const products=await tx.product.findMany({where:{id:{in:input.items.map(x=>x.productId)},isActive:true,archived:false}}); const pmap=new Map(products.map(p=>[p.id,p]));
  let subtotal=new Prisma.Decimal(0); const req=new Map<string,number>(); const snapshots:{productId:string;nameSnapshot:string;priceSnapshot:Prisma.Decimal;quantity:number;itemTotal:Prisma.Decimal;addons:{addonId:string;nameSnapshot:string;priceSnapshot:Prisma.Decimal}[]}[]=[]
  for(const item of input.items){const p=pmap.get(item.productId);if(!p)throw new Error('One or more selected products are no longer available.');if(!Number.isInteger(item.quantity)||item.quantity<1)throw new Error('Product quantities must be whole numbers of at least 1.');let addonTotal=new Prisma.Decimal(0);const addons=[] as {addonId:string;nameSnapshot:string;priceSnapshot:Prisma.Decimal}[];for(const aid of item.addonIds){const a=await tx.addon.findFirst({where:{id:aid,isActive:true,productAddons:{some:{productId:p.id}}}});if(!a)throw new Error('One or more selected add-ons are unavailable.');addonTotal=addonTotal.add(a.price);addons.push({addonId:a.id,nameSnapshot:a.name,priceSnapshot:a.price});for(const c of await tx.addonComponent.findMany({where:{addonId:a.id}}))req.set(c.inventoryItemId,(req.get(c.inventoryItemId)||0)+c.quantity.toNumber()*item.quantity)}if(p.type==='DIRECT_INVENTORY'&&p.inventoryItemId)req.set(p.inventoryItemId,(req.get(p.inventoryItemId)||0)+item.quantity);if(p.type==='COMPONENT_BASED')for(const c of await tx.productComponent.findMany({where:{productId:p.id}}))req.set(c.inventoryItemId,(req.get(c.inventoryItemId)||0)+c.quantity.toNumber()*item.quantity);const total=p.price.add(addonTotal).mul(item.quantity);subtotal=subtotal.add(total);snapshots.push({productId:p.id,nameSnapshot:p.name,priceSnapshot:p.price,quantity:item.quantity,itemTotal:total,addons})}
  let discount=new Prisma.Decimal(0);const dv=Math.max(0,input.discountValue||0);if(input.discountType==='PERCENTAGE')discount=subtotal.mul(Math.min(dv,100)).div(100);else if(input.discountType==='FIXED')discount=new Prisma.Decimal(Math.min(dv,subtotal.toNumber()));const total=subtotal.sub(discount);const received=new Prisma.Decimal(input.amountReceived||0);if(input.paymentMethod==='CASH'&&received.lessThan(total))throw new Error('Insufficient cash received. Please enter an amount equal to or greater than the order total.');if(input.paymentMethod==='ONLINE'&&!input.paymentProofPath)throw new Error('Payment proof is required for online payment.');
  const inv=await tx.inventoryItem.findMany({where:{id:{in:[...req.keys()]}}});for(const [id,needed] of req){const row=inv.find(x=>x.id===id);if(!row||row.quantity.toNumber()<needed)throw new Error(`Insufficient stock for ${row?.name||'a required inventory item'}.`)}
  const prefix=(await tx.businessSetting.findFirst())?.orderPrefix||'IIU';const code=`${prefix}-${Date.now().toString(36).toUpperCase()}`;const order=await tx.order.create({data:{code,status:'COMPLETED',customerId:input.customerId||null,createdById:input.userId,subtotal,discountType:input.discountType,discountValue:new Prisma.Decimal(dv),discountAmount:discount,total,completedAt:new Date(),items:{create:snapshots.map(s=>({productId:s.productId,nameSnapshot:s.nameSnapshot,priceSnapshot:s.priceSnapshot,quantity:s.quantity,itemTotal:s.itemTotal,addons:{create:s.addons}}))},payment:{create:{method:input.paymentMethod,amount:total,amountReceived:input.paymentMethod==='CASH'?received:total,changeDue:input.paymentMethod==='CASH'?received.sub(total):new Prisma.Decimal(0),proofPath:input.paymentProofPath||null,createdById:input.userId}}}});for(const [id,needed] of req){const row=inv.find(x=>x.id===id)!;const updated=await tx.inventoryItem.updateMany({where:{id,quantity:{gte:new Prisma.Decimal(needed)}},data:{quantity:{decrement:new Prisma.Decimal(needed)}}});if(updated.count!==1)throw new Error('Inventory changed while completing this order. Please try again.');await tx.inventoryMovement.create({data:{inventoryItemId:id,orderId:order.id,quantityBefore:row.quantity,quantityChanged:new Prisma.Decimal(-needed),quantityAfter:row.quantity.sub(needed),movementType:'ORDER_DEDUCTION',userId:input.userId}})}await tx.auditLog.create({data:{userId:input.userId,action:'ORDER_COMPLETED',entity:'Order',entityId:order.id,newValue:{total:total.toString(),code}}});return order
 },{isolationLevel:'Serializable'})
}
